@extends->layout

@section->main_content

<div class="row row-centered row-eq-height-sm">
    <div class="col-xs-10 col-md-3 col-lg-3 col-xs-offset-1 col-md-offset-1 col-lg-offset-1 col-centered">
        <a href="/task/1">
            <div class="panel panel-default">
                <div class="panel-heading">Palindrome test</div>
                <div class="panel-body">
                    <p>Tests string whether if it's palindrome or not.</p>
                </div>
            </div>
        </a>
    </div>

    <div class="col-xs-10 col-md-3 col-lg-3 col-xs-offset-1 col-md-offset-0 col-lg-offset-0 col-centered">
        <a href="/task/2">
            <div class="panel panel-default">
                <div class="panel-heading">Number to n-th power</div>
                <div class="panel-body">
                    <p>Returns number m, powered to n (m<sup>n</sup>)</p>
                </div>
            </div>
        </a>
    </div>

    <div class="col-xs-10 col-md-3 col-lg-3 col-xs-offset-1 col-md-offset-0 col-lg-offset-0 col-centered">
        <a href="/task/3">
            <div class="panel panel-default">
                <div class="panel-heading">Most common array element</div>
                <div class="panel-body">
                    <p>Returns most common array element. Array can consist of strings or numbers.</p>
                </div>
            </div>
        </a>
    </div>
</div>


<div class="row row-centered row-eq-height-sm">
    <div class="col-xs-10 col-md-3 col-lg-3 col-xs-offset-1 col-md-offset-1 col-lg-offset-1 col-centered">
        <a href="/task/4">
            <div class="panel panel-default">
                <div class="panel-heading">Lowest array number</div>
                <div class="panel-body">
                    <p>Returns lowest number in a given array</p>
                </div>
            </div>
        </a>
    </div>

    <div class="col-xs-10 col-md-3 col-lg-3 col-xs-offset-1 col-md-offset-0 col-lg-offset-0 col-centered">
        <a href="/task/5">
            <div class="panel panel-default">
                <div class="panel-heading">Longest common string</div>
                <div class="panel-body">
                    <p>Returns longest common string from two provided strings</p>
                </div>
            </div>
        </a>
    </div>

    <div class="col-xs-10 col-md-3 col-lg-3 col-xs-offset-1 col-md-offset-0 col-lg-offset-0 col-centered">
        <a href="/task/6">
            <div class="panel panel-default">
                <div class="panel-heading">Group division</div>
                <div class="panel-body">
                    <p>Divides numbers into groups in a way that sum of every group is as close as possible</p>
                </div>
            </div>
        </a>
    </div>
</div>


<div class="row row-centered row-eq-height-sm">
    <div class="col-xs-10 col-md-3 col-lg-3 col-xs-offset-1 col-md-offset-1 col-lg-offset-1 col-centered">
        <a href="/task/7">
            <div class="panel panel-default">
                <div class="panel-heading">Divisible numbers</div>
                <div class="panel-body">
                    <p>Prints out numbers divisible by 3 as 'LOCA', by 5 as 'STIC' and by 3 and 5 as 'LOCASTIC'</p>
                </div>
            </div>
        </a>
    </div>

    <div class="col-xs-10 col-md-3 col-lg-3 col-xs-offset-1 col-md-offset-0 col-lg-offset-0 col-centered">
        <a href="/task/8">
            <div class="panel panel-default">
                <div class="panel-heading">Files and folders show</div>
                <div class="panel-body">
                    <p>Shows this app's folder structure with files</p>
                </div>
            </div>
        </a>
    </div>
</div>