@extends->layout

@section->main_content

<div class="row">
    <div class="col-xs-12 col-md-8 col-lg-6 col-md-offset-2 col-lg-offset-3">

        <p>Numbers divisible by 3 or 5</p>

        <form action="/task/7" method="post">
            <input type="submit" value="Show" class="btn btn-primary">
        </form>

        <a href="/"><button class="btn btn-warning">Go Back</button></a>

    </div>
</div>


<div class="row">
    <div class="col-xs-12 col-md-8 col-lg-6 col-md-offset-2 col-lg-offset-3">

        <p>
            <?php
            if(isset($_SESSION['data'])){
                foreach ($_SESSION['data'] as $resultElem) echo '<br>' . $resultElem;
                unset($_SESSION['data']);
            }
            ?>
        </p>

    </div>
</div>