@extends->layout

@section->main_content

<div class="row">
    <div class="col-xs-12 col-md-8 col-lg-6 col-md-offset-2 col-lg-offset-3">

        <p>Recursive folder reading</p>

        <form action="/task/8" method="post">
            <input type="submit" value="Show app directories" class="btn btn-primary">
        </form>

        <a href="/"><button class="btn btn-warning">Go Back</button></a>

    </div>
</div>


<div class="row">
    <div class="col-xs-12 col-md-8 col-lg-6 col-md-offset-2 col-lg-offset-3">

        <p>
            <?php
            if(isset($_SESSION['data'])){
                $result = $_SESSION['data'];
                // Prettifying dir structure to look as expanded folders
                $dirContentsSorted = array();
                foreach ($result['dirContents'] as $elem) {
                    $pathArray = explode('/', $elem['path']);
                    if($elem['type']=='folder'){
                        // http://stackoverflow.com/a/7508437
                        $ref = &$dirContentsSorted;
                        while($key = array_shift($pathArray)){
                            $ref = &$ref[$key];
                        }
                        $ref = array();
                    }
                    if($elem['type']=='file'){
                        $filename = $pathArray[count($pathArray)-1];
                        //array_pop($pathArray);
                        $ref = &$dirContentsSorted;
                        while($key = array_shift($pathArray)){
                            $ref = &$ref[$key];
                        }
                        $ref = $filename;
                    }
                }

                echo '<pre>'; print_r($result['dirContents']); echo '</pre>';
                echo '<pre>'; print_r($dirContentsSorted); echo '</pre>';
                unset($_SESSION['data']);
            }
            ?>
        </p>

    </div>
</div>