@extends->layout

@section->main_content

<div class="row">
    <div class="col-xs-12 col-md-8 col-lg-6 col-md-offset-2 col-lg-offset-3">

        <p>Palindrome test</p>

        <form action="/task/1" method="post">
            <label for="palindrome">Enter string to be checked:</label>
            <input type="text" name="palindrome" id="palindrome">
            <input type="submit" value="Check" class="btn btn-primary">
        </form>

        <a href="/"><button class="btn btn-warning">Go Back</button></a>

    </div>
</div>


<div class="row">
    <div class="col-xs-12 col-md-8 col-lg-6 col-md-offset-2 col-lg-offset-3">

        <p>
            <?php
            if(isset($_SESSION['data'])){
                // Function result is true or false
                echo ($_SESSION['data']) ? 'Given string is a palindrome' : 'Given string is not a palindrome';
                unset($_SESSION['data']);
            }
            ?>
        </p>

    </div>
</div>