@extends->layout

@section->main_content

<div class="row">
    <div class="col-xs-12 col-md-8 col-lg-6 col-md-offset-2 col-lg-offset-3">

        <p>Number to n-th power</p>

        <form action="/task/2" method="post">
            <label for="number1">Enter base number:</label>
            <input type="number" name="number1" id="number1">
            <label for="number2">Enter exponent number:</label>
            <input type="number" name="number2" id="number2">
            <input type="submit" value="Calculate" class="btn btn-primary">
        </form>

        <a href="/"><button class="btn btn-warning">Go Back</button></a>

    </div>
</div>


<div class="row">
    <div class="col-xs-12 col-md-8 col-lg-6 col-md-offset-2 col-lg-offset-3">

        <p>
            <?php
            if(isset($_SESSION['data'])){
                $result = $_SESSION['data'];
                echo ($result!==false) ? $result['firstNum'].'<sup>'.$result['secondNum'].'</sup> = '.$result['result'] : 'Unable to perform calculation';
                unset($_SESSION['data']);
            }
            ?>
        </p>

    </div>
</div>